        self.stuInfoList.setRowCount(1)
        self.stuInfoList.setItem(0,0,QTableWidgetItem(str(1)))
        self.stuInfoList.setItem(0,1,QTableWidgetItem(str(2)))
        self.stuInfoList.setItem(0,2,QTableWidgetItem(str(3)))
        self.stuInfoList.setItem(0,3,QTableWidgetItem(str(4)))

        self.stuInfoList.setRowCount(2)
        self.stuInfoList.setItem(1,0,QTableWidgetItem(str(2)))
        self.stuInfoList.setItem(1,1,QTableWidgetItem(str(3)))
        self.stuInfoList.setItem(1,2,QTableWidgetItem(str(4)))
        self.stuInfoList.setItem(1,3,QTableWidgetItem(str(5)))